### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by l-Nuril-l** [ImTheSquid/SplitLargeFiles#17] opened 2022-09-07 17:55 UTC
> Update Discord.

na i have it updated i think its cuz discord cant upload more than 10 files at the same time cuz when i make it so it only tries to upload 10 files it works

_Originally posted by @mcpeadventure09 in https://github.com/ImTheSquid/SplitLargeFiles/issues/15#issuecomment-1221385329_
![image](https://user-images.githubusercontent.com/49325887/188946742-c03316de-b974-45f9-a288-f8addb27b208.png)

**Comment by ImTheSquid** [comment] 2022-09-09 03:49
I'll look into this

**Comment by ImTheSquid** [comment] 2022-09-12 18:52
Issue confirmed, I'll start working on a fix

**Comment by l-Nuril-l** [comment] 2022-09-12 23:45
> Issue confirmed, I'll start working on a fix

Still not working

**Comment by JustOptimize** [comment] 2022-09-18 08:45
It looks like we are getting rate limited: 
![image](https://user-images.githubusercontent.com/54294419/190893664-7b575084-d3a4-4cbe-adfc-53993a5f4ac0.png)

**Comment by ImTheSquid** [comment] 2022-09-18 17:04
I'm looking into sending the files as multiple messages like I used to before the new upload system was introduced.

**Comment by ImTheSquid** [comment] 2022-09-18 23:23
Should be fixed with latest commit

**Closed by ImTheSquid** 2022-09-18 23:23 UTC
Labels: bug
